spring:
  datasource:
    url: jdbc:postgresql://citus_master:5432/userdb
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none # Or 'none' based on your preference
    show-sql: true